# Use root/example as user/password credentials
version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - es-net
  mysql:
    image: mysql:8.0.33
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shop_close
      MYSQL_USER: lenam
      MYSQL_PASSWORD: 123456
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - es-net
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - es-net
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    # environment:
    #   RABBITMQ_DEFAULT_PASS: 123456
    #   RABBITMQ_DEFAULT_USER: root
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/

networks:
  es-net:
    driver: bridge
